// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/applications" | "/applications/[id]" | "/dashboard" | "/login" | "/services"
type AppRouteHandlerRoutes = "/api/v1/[...path]" | "/api/v1/applications" | "/api/v1/applications/[id]" | "/api/v1/applications/[id]/identity-attempts" | "/api/v1/applications/[id]/identity-attempts/[attemptId]/retry" | "/api/v1/applications/[id]/identity-attempts/latest" | "/api/v1/applications/[id]/payments" | "/api/v1/applications/[id]/sections/[sectionKey]" | "/api/v1/applications/[id]/steps/[sectionKey]/complete" | "/api/v1/appointments" | "/api/v1/appointments/[id]/cancel" | "/api/v1/auth/logout" | "/api/v1/auth/request-otp" | "/api/v1/auth/verify-otp" | "/api/v1/health" | "/api/v1/health/ready" | "/api/v1/licences" | "/api/v1/licences/[id]" | "/api/v1/me" | "/api/v1/offers/[id]/accept" | "/api/v1/offers/[id]/decline" | "/api/v1/payment-provider/events" | "/api/v1/payments/[id]" | "/api/v1/rtos" | "/api/v1/rtos/[id]/availability" | "/api/v1/rtos/[id]/slots" | "/api/v1/services" | "/api/v1/waitlist" | "/api/v1/waitlist/[id]" | "/api/v1/waitlist/process"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/v1/[...path]": { "path": string[]; }
  "/api/v1/applications": {}
  "/api/v1/applications/[id]": { "id": string; }
  "/api/v1/applications/[id]/identity-attempts": { "id": string; }
  "/api/v1/applications/[id]/identity-attempts/[attemptId]/retry": { "id": string; "attemptId": string; }
  "/api/v1/applications/[id]/identity-attempts/latest": { "id": string; }
  "/api/v1/applications/[id]/payments": { "id": string; }
  "/api/v1/applications/[id]/sections/[sectionKey]": { "id": string; "sectionKey": string; }
  "/api/v1/applications/[id]/steps/[sectionKey]/complete": { "id": string; "sectionKey": string; }
  "/api/v1/appointments": {}
  "/api/v1/appointments/[id]/cancel": { "id": string; }
  "/api/v1/auth/logout": {}
  "/api/v1/auth/request-otp": {}
  "/api/v1/auth/verify-otp": {}
  "/api/v1/health": {}
  "/api/v1/health/ready": {}
  "/api/v1/licences": {}
  "/api/v1/licences/[id]": { "id": string; }
  "/api/v1/me": {}
  "/api/v1/offers/[id]/accept": { "id": string; }
  "/api/v1/offers/[id]/decline": { "id": string; }
  "/api/v1/payment-provider/events": {}
  "/api/v1/payments/[id]": { "id": string; }
  "/api/v1/rtos": {}
  "/api/v1/rtos/[id]/availability": { "id": string; }
  "/api/v1/rtos/[id]/slots": { "id": string; }
  "/api/v1/services": {}
  "/api/v1/waitlist": {}
  "/api/v1/waitlist/[id]": { "id": string; }
  "/api/v1/waitlist/process": {}
  "/applications": {}
  "/applications/[id]": { "id": string; }
  "/dashboard": {}
  "/login": {}
  "/services": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
