// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/applications/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/applications/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/applications/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/applications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/applications">> = Specific
  const handler = {} as typeof import("../../src/app/applications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/services/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services">> = Specific
  const handler = {} as typeof import("../../src/app/services/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/v1/[...path]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/[...path]">> = Specific
  const handler = {} as typeof import("../../src/app/api/v1/[...path]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/v1/applications/[id]/identity-attempts/[attemptId]/retry/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/applications/[id]/identity-attempts/[attemptId]/retry">> = Specific
  const handler = {} as typeof import("../../src/app/api/v1/applications/[id]/identity-attempts/[attemptId]/retry/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/v1/applications/[id]/identity-attempts/latest/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/applications/[id]/identity-attempts/latest">> = Specific
  const handler = {} as typeof import("../../src/app/api/v1/applications/[id]/identity-attempts/latest/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/v1/applications/[id]/identity-attempts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/applications/[id]/identity-attempts">> = Specific
  const handler = {} as typeof import("../../src/app/api/v1/applications/[id]/identity-attempts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/v1/applications/[id]/payments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/applications/[id]/payments">> = Specific
  const handler = {} as typeof import("../../src/app/api/v1/applications/[id]/payments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/v1/applications/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/applications/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/v1/applications/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/v1/applications/[id]/sections/[sectionKey]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/applications/[id]/sections/[sectionKey]">> = Specific
  const handler = {} as typeof import("../../src/app/api/v1/applications/[id]/sections/[sectionKey]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/v1/applications/[id]/steps/[sectionKey]/complete/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/applications/[id]/steps/[sectionKey]/complete">> = Specific
  const handler = {} as typeof import("../../src/app/api/v1/applications/[id]/steps/[sectionKey]/complete/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/v1/applications/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/applications">> = Specific
  const handler = {} as typeof import("../../src/app/api/v1/applications/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/v1/appointments/[id]/cancel/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/appointments/[id]/cancel">> = Specific
  const handler = {} as typeof import("../../src/app/api/v1/appointments/[id]/cancel/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/v1/appointments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/appointments">> = Specific
  const handler = {} as typeof import("../../src/app/api/v1/appointments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/v1/auth/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/auth/logout">> = Specific
  const handler = {} as typeof import("../../src/app/api/v1/auth/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/v1/auth/request-otp/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/auth/request-otp">> = Specific
  const handler = {} as typeof import("../../src/app/api/v1/auth/request-otp/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/v1/auth/verify-otp/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/auth/verify-otp">> = Specific
  const handler = {} as typeof import("../../src/app/api/v1/auth/verify-otp/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/v1/health/ready/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/health/ready">> = Specific
  const handler = {} as typeof import("../../src/app/api/v1/health/ready/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/v1/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/health">> = Specific
  const handler = {} as typeof import("../../src/app/api/v1/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/v1/licences/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/licences/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/v1/licences/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/v1/licences/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/licences">> = Specific
  const handler = {} as typeof import("../../src/app/api/v1/licences/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/v1/me/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/me">> = Specific
  const handler = {} as typeof import("../../src/app/api/v1/me/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/v1/offers/[id]/accept/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/offers/[id]/accept">> = Specific
  const handler = {} as typeof import("../../src/app/api/v1/offers/[id]/accept/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/v1/offers/[id]/decline/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/offers/[id]/decline">> = Specific
  const handler = {} as typeof import("../../src/app/api/v1/offers/[id]/decline/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/v1/payment-provider/events/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/payment-provider/events">> = Specific
  const handler = {} as typeof import("../../src/app/api/v1/payment-provider/events/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/v1/payments/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/payments/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/v1/payments/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/v1/rtos/[id]/availability/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/rtos/[id]/availability">> = Specific
  const handler = {} as typeof import("../../src/app/api/v1/rtos/[id]/availability/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/v1/rtos/[id]/slots/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/rtos/[id]/slots">> = Specific
  const handler = {} as typeof import("../../src/app/api/v1/rtos/[id]/slots/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/v1/rtos/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/rtos">> = Specific
  const handler = {} as typeof import("../../src/app/api/v1/rtos/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/v1/services/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/services">> = Specific
  const handler = {} as typeof import("../../src/app/api/v1/services/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/v1/waitlist/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/waitlist/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/v1/waitlist/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/v1/waitlist/process/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/waitlist/process">> = Specific
  const handler = {} as typeof import("../../src/app/api/v1/waitlist/process/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/v1/waitlist/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/waitlist">> = Specific
  const handler = {} as typeof import("../../src/app/api/v1/waitlist/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
