var R=require("../chunks/ssr/[turbopack]_runtime.js")("server/app/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0d1s3o2._.js")
R.c("server/chunks/ssr/_1_lk_hq._.js")
R.c("server/chunks/ssr/0g_d_next_dist_027m64r._.js")
R.c("server/chunks/ssr/1a7c_zod_v4_classic_external_0cdqsh1.js")
R.c("server/chunks/ssr/_0fhpq07._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0w9x5mz._.js")
R.c("server/chunks/ssr/[root-of-the-server]__03u1zx_._.js")
R.c("server/chunks/ssr/[root-of-the-server]__158e4hl._.js")
R.c("server/chunks/ssr/_0viabim._.js")
R.c("server/chunks/ssr/apps_web_src_lib_utils_ts_0_nz7pu._.js")
R.c("server/chunks/ssr/0g_d_next_dist_client_components_1-tmkva._.js")
R.c("server/chunks/ssr/0g_d_next_dist_client_components_builtin_forbidden_0lnp5el.js")
R.c("server/chunks/ssr/0g_d_next_dist_client_components_builtin_unauthorized_0kpzkdi.js")
R.c("server/chunks/ssr/0g_d_next_dist_client_components_builtin_global-error_1uq317m.js")
R.c("server/chunks/ssr/_1xu5h4-._.js")
R.m(38262)
module.exports=R.m(38262).exports
